# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - test2-ray-chunkit-chung

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4f365340ad404d89a0a413ade39e3f59 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4ee2aeb705eb46bf9e9074756b26e549 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4f365340ad404d89a0a413ade39e3f59 }}/raychung/azure-docker-react-hello:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'test2-ray-chunkit-chung'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_60716f88306441a6bcc2a6c8c3f94f25 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4f365340ad404d89a0a413ade39e3f59 }}/raychung/azure-docker-react-hello:${{ github.sha }}'